### ISSUE TITLE
Get value not working

### ISSUE THREAD

**Issue by tusharvb19** [ubidots/ubidots-arduino-gprs#11]
The get value code seems having some bug!!!
I tried the version 1 but it was giving constant value 1 or 1.0 and now version 2 is not getting output after SAPBR=1,1

**Comment by Metavix** [comment]
@tusharvb19  hello!
Could you post here all of the Serial monitor. Thanks It will be help me to help you

**Comment by tusharvb19** [comment]
Now i am getting this at serial monitor...

Response of GPRS:

Response of GPRS:
AT
OK

Response of GPRS:
AT+CSQ
+CSQ: 17,0

OK

Response of GPRS:
AT+CGATT?
+CGATT: 1

OK

Response of GPRS:
AT+SAPBR=3,1,"CONTYPE","GPRS"
OK

Response of GPRS:
AT+SAPBR=3,1,"APN","www"
OK

Response of GPRS:
AT+SAPBR=3,1,"USER",""
OK

Response of GPRS:
AT+SAPBR=3,1,"PWD",""
OK

Response of GPRS:
AT+SAPBR=1,1
OK

Response of GPRS:
AT+SAPBR=2,1
+SAPBR: 1,1,"10.136.192.121"

OK

Response of GPRS:
AT+CIPMUX=0
OK

Response of GPRS:
AT+CIPSTART="TCP","translate.ubidots.com","9010"
OK

CONNECT OK

Response of GPRS:
AT+CIPSEND=104

> Response of GPRS:
> GPRS/2.0|LV|1ppM5HWgmeSlIgEMdTpeoU06P0LppV|Your_data_source_identifier_here:57947bb8762542115059db66|end
> SEND OK
> ER|Data Source not found
> GPRS/2.0|LV|1ppM5HWgmeSlIgEMdTpeoU06P0LppV|Your_data_source_identifier_here:57947bb8762542115059db66|end
> SEND OK
> ER|Data Source not found
> Response of GPRS:
> AT+CIPCLOSE
> CLOSE OK

Response of GPRS:
AT+CIPSHUT
SHUT OK
0.00
0.00

**Comment by tusharvb19** [comment]
After replacing the Your_data_source_identifier_here with my data source label giving the same output!!!
I am not getting the GET request.

**Comment by tusharvb19** [comment]
Also while trying TCP i got the following response and again unsuccessful performing GET!!!

AT+CIPSTART="tcp","things.ubidots.com","80"

OK

CONNECT OK
AT+CIPSEND
GET /api/v1.6/variables/57947bb8762542115059db66
/values?token=1ppM5HWgmeSlIgEMdTpeoU06P0LppV
&page_size=1 HTTP/1.1
Host: things.ubidots.com


SEND OK
<html>
<head><title>302 Found</title></head>
<bAT+CIPCLOSE

ERROR

Can anyone help me out to solve this.

**Comment by Metavix** [comment]
@tusharvb19 
Nice i know where is the problem of your code of the first comment. Please paste here your code to change the lines with the error and do it work's!
I'm talking about the code of this Serial response:

```
  Response of GPRS:
  AT+CIPSEND=104

  Response of GPRS:
  GPRS/2.0|LV|1ppM5HWgmeSlIgEMdTpeoU06P0LppV|Your_data_source_identifier_here:57947bb87  62542115059db66|end
  SEND OK
  ER|Data Source not found
    GPRS/2.0|LV|1ppM5HWgmeSlIgEMdTpeoU06P0LppV|Your_data_source_identifier_here:57947bb8762542115059db66|end
  SEND OK
  ER|Data Source not found
  Response of GPRS:
  AT+CIPCLOSE
  CLOSE OK
  Response of GPRS:
  AT+CIPSHUT
  SHUT OK
  0.00
  0.00
```

**Comment by tusharvb19** [comment]
This is my code-

#include <UbidotsArduinoGPRS.h>
#include <SoftwareSerial.h> 

#define APN "www" 
#define USER ""  // If your apn doesnt have username just put ""
#define PASS ""  // If your apn doesnt have password just put ""
#define TOKEN "1ppM5HWgmeSlIgEMdTpeoU06P0LppV"  // Replace it with your Ubidots token
#define DATA_SOURCE_IDENTIFIER "mds"
#define VARIABLE_IDENTIFIER "temperature"

Ubidots client(TOKEN);

SoftwareSerial gprs = SoftwareSerial(2,3);
SoftwareSerial *GPRSSerial = &gprs;

void setup() {
  Serial.begin(115200);
  GPRSSerial->begin(19200);
  if (! client.init(*GPRSSerial)) {
    Serial.println(F("Couldn't find FONA"));
    while (1);
  }
  while (!client.setApn(APN,USER,PASS));
}

void loop() {
  float value = client.getValueWithDatasource(DATA_SOURCE_IDENTIFIER, VARIABLE_IDENTIFIER);
  Serial.println(value);
  delay(1000);
  Serial.println(value);
}

**Comment by Metavix** [comment]
@tusharvb19 Your data source identifier is mds?
This is a variable identifier and data source identifier:
![screenshot from 2016-08-18 15-48-09](https://cloud.githubusercontent.com/assets/8158682/17790367/b5d553e6-655b-11e6-8b32-9405b053faf2.png)
![screenshot from 2016-08-18 15-48-13](https://cloud.githubusercontent.com/assets/8158682/17790366/b5d1863a-655b-11e6-8307-f87e15ad5003.png)

**Comment by tusharvb19** [comment]
I have inputted the same...Data source identifier-source label and variable label but still it is not working!!!
The code is now giving output as error authorising credentials...
The another tcp raw code(direct AT commands) gives me output as
"302 Found"

**Comment by Metavix** [comment]
Hello @tusharvb19  sorry, my last response was wrong, it isn't with labels, it is with data source tag and variable tag:

![screenshot from 2016-08-19 08-22-16](https://cloud.githubusercontent.com/assets/8158682/17811111/a73b96de-65e6-11e6-8c79-348a005a5605.png)
![screenshot from 2016-08-19 08-22-08](https://cloud.githubusercontent.com/assets/8158682/17811113/a73fdd0c-65e6-11e6-9619-ae22fa155529.png)

Really sorry i was wrong. If you put a tag to your data source named "mds" and tag to a variable "temperature" and uses the next code it will work:

``` cpp
#include <UbidotsArduinoGPRS.h>
#include <SoftwareSerial.h> 
//Serial Relay - Arduino will patch a 
//serial link between the computer and the GPRS Shield
//at 19200 bps 8-N-1
//Computer is connected to Hardware UART
//GPRS Shield is connected to the Software UART 

#define APN "www" 
#define USER "" // If your apn doesnt have username just put ""
#define PASS "" // If your apn doesnt have password just put ""
#define TOKEN "1ppM5HWgmeSlIgEMdTpeoU06P0LppV" // Replace it with your Ubidots token
#define DATA_SOURCE_IDENTIFIER "mds"
#define VARIABLE_IDENTIFIER "temperature"

Ubidots client(TOKEN);  

void setup() {
  Serial.begin(115200);
  GPRSSerial->begin(19200);
  if (! client.init(*GPRSSerial)) {
    Serial.println(F("Couldn't find FONA"));
    while (1);
  }
  while (!client.setApn(APN,USER,PASS));
}

void loop() {
  float value = client.getValueWithDatasource(DATA_SOURCE_IDENTIFIER, VARIABLE_IDENTIFIER));
  Serial.println(value);
  delay(1000);
  Serial.println(value);
}
```

**Comment by tusharvb19** [comment]
Finally got that working!!!
Thank you very much...
really thanx..

**Comment by Metavix** [comment]
@tusharvb19  no problem. Thank to you and sorry again for my wrong answeer the first time.
