### ISSUE TITLE
Real time approximate location possible?

### ISSUE THREAD

**Issue by tusharvb19** [ubidots/ubidots-arduino-gprs#12]
Can it be possible to integrate the real time approx location found using this AT command-

AT+CIPGSMLOC=1,1 // triangulate
+CIPGSMLOC: 0,19.667806,49.978185,2014/03/20,14:12:27

OK

taken from-
http://signusx.com/sim900-geolocalization-without-gps-atcipgsmloc/

**Comment by jotathebest** [comment]
this is something related with a custom firmware rather with our library, closing as the link shared is not available anymore
